<?xml version="1.0"?>


<!DOCTYPE rdf:RDF [
    <!ENTITY owl "http://www.w3.org/2002/07/owl#" >
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
]>


<rdf:RDF xmlns="http://www.test.org/XMLNS#"
     xml:base="http://www.test.org/XMLBASE"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <owl:Ontology rdf:about="#ns.rdf"/>
    
    <owl:AnnotationProperty rdf:about="http://www.test.org/XMLNS#P"/>


    <owl:Class rdf:about="A"/>
    <owl:Class rdf:about="#B"/>
    <owl:Class rdf:about="/C"/>
    
    <owl:Class rdf:about="D">
      <P>test</P>
      <rdfs:subClassOf rdf:resource="A"/>
      <rdfs:subClassOf rdf:resource="#B"/>
      <rdfs:subClassOf rdf:resource="/C"/>
    </owl:Class>
    
</rdf:RDF>



<!-- Generated by the OWL API (version 3.4.2) http://owlapi.sourceforge.net -->

