<?xml version="1.0"?>
<rdf:RDF xmlns="http://test.org/test_ontoslash2/"
     xml:base="http://test.org/test_ontoslash2"
     xmlns:schema="http://schema.org/"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace">
    <owl:Ontology rdf:about="http://test.org/test_ontoslash2">
         <owl:imports rdf:resource="http://www.semanticweb.org/jiba/ontologies/2017/0/test"/>
         <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">TEST</rdfs:comment>
    </owl:Ontology>
    


    <owl:Class rdf:about="http://test.org/test_ontoslash2/Class1">
    </owl:Class>
    
    <owl:Class rdf:about="http://test.org/test_ontoslash2/Class2">
    </owl:Class>
    
</rdf:RDF>



<!-- Generated by the OWL API (version 4.2.6.20160910-2108) https://github.com/owlcs/owlapi -->

