<?xml version="1.0"?>


<!DOCTYPE rdf:RDF [
    <!ENTITY owl "http://www.w3.org/2002/07/owl#" >
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
    <!ENTITY owlready_ontology "http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl#" >
]>


<rdf:RDF xmlns="http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl#"
     xml:base="http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owlready_ontology="http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl#">
    <owl:Ontology rdf:about="http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl">
        <owlready_ontology:python_module>test_mixed</owlready_ontology:python_module>
        <owl:imports rdf:resource="http://www.lesfleursdunormal.fr/static/_downloads/owlready_ontology.owl"/>
    </owl:Ontology>
    


    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Classes
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    


    <!-- http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl#Child -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl#Child">
        <rdfs:subClassOf rdf:resource="http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl#Parent"/>
    </owl:Class>
    


    <!-- http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl#Parent -->

    <owl:Class rdf:about="http://www.semanticweb.org/jiba/ontologies/2017/2/test_mixed.owl#Parent"/>
</rdf:RDF>



<!-- Generated by the OWL API (version 3.4.2) http://owlapi.sourceforge.net -->

